# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.12-alpine

# Install build dependencies
RUN apk add --no-cache gcc musl-dev libffi-dev openssl-dev

WORKDIR /app

# Copy project files including README.md
COPY pyproject.toml README.md ./
COPY src ./src

# Upgrade pip and install the package
RUN pip install --upgrade pip \
    && pip install .

# Default command runs the MCP server
CMD ["spotify-mcp"]
